name: github action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # You can change this to your desired Node.js version

      - name: Go to react app directory
        run: cd react-typescript-app

      - name: Install packages
        run: npm install

      - name: Run the tests
        run: npm test
